// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63BHxBKpL_Nm5QP8OogglVeZ_y2qDkg0',
    appId: '1:313802675672:web:5a9ad512eef104fc61cead',
    messagingSenderId: '313802675672',
    projectId: 'kyrgyztest-app',
    authDomain: 'kyrgyztest-app.firebaseapp.com',
    storageBucket: 'kyrgyztest-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAcBWV8SEitiZSNKFiyVf0qhzACRxy4nU',
    appId: '1:313802675672:android:e475fd7d2771156e61cead',
    messagingSenderId: '313802675672',
    projectId: 'kyrgyztest-app',
    storageBucket: 'kyrgyztest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB6SMFwl4f3X0QE_mb4GPcmghq1bzNpyQ',
    appId: '1:313802675672:ios:f80644ebf161bdf361cead',
    messagingSenderId: '313802675672',
    projectId: 'kyrgyztest-app',
    storageBucket: 'kyrgyztest-app.firebasestorage.app',
    androidClientId: '313802675672-1u4sr3vrmvuej8js00kig48pfq37v6jv.apps.googleusercontent.com',
    iosClientId: '313802675672-75v5a1vv0gnj8rtd17de1rcr9hgk9pg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyrgyztestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB6SMFwl4f3X0QE_mb4GPcmghq1bzNpyQ',
    appId: '1:313802675672:ios:f80644ebf161bdf361cead',
    messagingSenderId: '313802675672',
    projectId: 'kyrgyztest-app',
    storageBucket: 'kyrgyztest-app.firebasestorage.app',
    androidClientId: '313802675672-1u4sr3vrmvuej8js00kig48pfq37v6jv.apps.googleusercontent.com',
    iosClientId: '313802675672-75v5a1vv0gnj8rtd17de1rcr9hgk9pg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyrgyztestapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC63BHxBKpL_Nm5QP8OogglVeZ_y2qDkg0',
    appId: '1:313802675672:web:36aeac97b4a7615361cead',
    messagingSenderId: '313802675672',
    projectId: 'kyrgyztest-app',
    authDomain: 'kyrgyztest-app.firebaseapp.com',
    storageBucket: 'kyrgyztest-app.firebasestorage.app',
  );

}